port: ${PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: esun-library-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jackson:
    time-zone: Asia/Taipei

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

logging:
  level:
    org.springframework.jdbc.core: INFO